### ISSUE TITLE
Make CI test gem installation

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-url#109]
Seen on https://github.com/sickill/rainbow/commit/30904393e61844304abc0f9f00226497fc1b8201

```yml

matrix:
  include:
    - rvm: 2.0.0

...

    - rvm: 2.2.6
      install: true # This skips 'bundle install'
      script: gem build rainbow && gem install *.gem
```
