### ISSUE TITLE
Update addressable to 2.6

### ISSUE THREAD

**Issue by jage** [twingly/twingly-url#132]
We're limiting to 2.5 currently:

https://github.com/twingly/twingly-url/blob/c2218e98ff0892e63adc483f4cf1c06e4f01f3ae/twingly-url.gemspec#L17

Did a quick test, but we need to either change our specs or look into why the protocol is updated:

```
Failures:

  1) Twingly::URL.parse when given valid urls does not ruin the url "hTTP://blog.twingly.com/"
     Failure/Error: expect(described_class.parse(valid_url).to_s).to eq(valid_url)

       expected: "hTTP://blog.twingly.com/"
            got: "http://blog.twingly.com/"

       (compared using ==)
     # ./spec/lib/twingly/url_spec.rb:124:in `block (5 levels) in <top (required)>'
```
