### ISSUE TITLE
Do not blow up on broken punycode URLs 

### ISSUE THREAD

**Issue by dentarg** [twingly/twingly-url#48]
The broken URLs

```diff
$ git diff
diff --git a/spec/lib/twingly/url_spec.rb b/spec/lib/twingly/url_spec.rb
index 85c2903..5786279 100644
--- a/spec/lib/twingly/url_spec.rb
+++ b/spec/lib/twingly/url_spec.rb
@@ -21,6 +21,8 @@ def invalid_urls
     "blablahttp://blog.twingly.com/",
     "gopher://blog.twingly.com/",
     "\n",
+    "http://xn--...-/",
+    "http://xn--t...-/",
   ]
 end
```

The failures

```
Failures:

  1) Twingly::URL#valid? returns false for an invalid URL (http://xn--...-/)
     Failure/Error: expect(described_class.parse(invalid_url).valid?).to be false
     NoMethodError:
       undefined method `size' for nil:NilClass
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:506:in `punycode_decode'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:97:in `block in to_unicode'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:95:in `map!'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:95:in `to_unicode'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/uri.rb:2050:in `display_uri'
     # ./lib/twingly/url.rb:35:in `internal_parse'
     # ./lib/twingly/url.rb:21:in `parse'
     # ./spec/lib/twingly/url_spec.rb:175:in `block (4 levels) in <top (required)>'

  2) Twingly::URL#valid? returns false for an invalid URL (http://xn--t...-/)
     Failure/Error: expect(described_class.parse(invalid_url).valid?).to be false
     Addressable::IDNA::PunycodeBadInput:
       Input is invalid.
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:563:in `punycode_decode'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:97:in `block in to_unicode'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:95:in `map!'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/idna/pure.rb:95:in `to_unicode'
     # /Users/dentarg/.gem/ruby/2.2.3/gems/addressable-2.3.8/lib/addressable/uri.rb:2050:in `display_uri'
     # ./lib/twingly/url.rb:35:in `internal_parse'
     # ./lib/twingly/url.rb:21:in `parse'
     # ./spec/lib/twingly/url_spec.rb:175:in `block (4 levels) in <top (required)>'
```

pushed an temporary branch with the specs, https://github.com/twingly/twingly-url/tree/tmp/issue/48
